-- Product Service Migration: Add canonical platform usage products
-- Version: 008
-- Date: 2026-04-09
-- Description: Seed billable SKUs for web services, python_repl execution,
--              and isA_Data user-facing data products.
-- Idempotent: Safe to run multiple times via INSERT ... ON CONFLICT ... DO UPDATE.

INSERT INTO product.products (
    product_id, product_name, product_code, description,
    category, product_type, base_price, currency, billing_interval,
    features, quota_limits, is_active, metadata,
    product_kind, fulfillment_type, inventory_policy, requires_shipping, tax_category
) VALUES
('web_search', 'Web Search', 'WEB-SEARCH',
 'Standard web search request through isA_OS web_service',
 'web_services', 'api_service', 0.0020, 'USD', 'per_request',
 '["search", "web", "query"]'::jsonb,
 '{"free_tier_requests": 1000}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "web_service", "operation_type": "search", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('web_deep_search', 'Web Deep Search', 'WEB-DEEP-SEARCH',
 'Multi-step deep web search through isA_OS web_service',
 'web_services', 'api_service', 0.0100, 'USD', 'per_request',
 '["search", "web", "deep-search"]'::jsonb,
 '{"free_tier_requests": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "web_service", "operation_type": "deep_search", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('web_search_summary', 'Web Search Summary', 'WEB-SEARCH-SUMMARY',
 'Search with summarization and citations through isA_OS web_service',
 'web_services', 'api_service', 0.0080, 'USD', 'per_request',
 '["search", "summary", "citations"]'::jsonb,
 '{"free_tier_requests": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "web_service", "operation_type": "search_summary", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('web_automation', 'Web Automation', 'WEB-AUTOMATION',
 'Browser automation execution through isA_OS web_service',
 'web_services', 'api_service', 0.0200, 'USD', 'per_execution',
 '["browser", "automation", "dom", "vision"]'::jsonb,
 '{"free_tier_executions": 25}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "web_service", "operation_type": "automation", "unit": "execution"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('python_repl_execution', 'Python REPL Execution', 'PYTHON-REPL-EXEC',
 'Sandboxed Python code execution through isA_OS python_repl',
 'developer_tools', 'computation', 0.0050, 'USD', 'per_execution',
 '["python", "sandbox", "execution"]'::jsonb,
 '{"free_tier_executions": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "python_repl", "operation_type": "code_execution", "unit": "execution"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.analytics.customer_360', 'Customer 360 View', 'DATA-CUSTOMER-360',
 'User-centric customer 360 data query exposed by isA_Data',
 'data_products', 'data_processing', 0.0040, 'USD', 'per_request',
 '["data", "analytics", "customer-360"]'::jsonb,
 '{"free_tier_requests": 500}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_360_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('curated.order.user_order_history', 'User Order History', 'DATA-ORDER-HISTORY',
 'User-centric order history data query exposed by isA_Data',
 'data_products', 'data_processing', 0.0030, 'USD', 'per_request',
 '["data", "orders", "history"]'::jsonb,
 '{"free_tier_requests": 500}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_order_history_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.behavior.user_patterns', 'User Behavior Patterns', 'DATA-BEHAVIOR-PATTERNS',
 'Behavior pattern analysis query exposed by isA_Data',
 'data_products', 'data_processing', 0.0060, 'USD', 'per_request',
 '["data", "behavior", "patterns"]'::jsonb,
 '{"free_tier_requests": 250}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_behavior_patterns_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.behavior.user_journeys', 'User Journey Analysis', 'DATA-USER-JOURNEYS',
 'User journey analysis query exposed by isA_Data',
 'data_products', 'data_processing', 0.0060, 'USD', 'per_request',
 '["data", "behavior", "journey"]'::jsonb,
 '{"free_tier_requests": 250}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_journey_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.behavior.engagement_metrics', 'User Engagement Metrics', 'DATA-ENGAGEMENT',
 'User engagement metrics query exposed by isA_Data',
 'data_products', 'data_processing', 0.0050, 'USD', 'per_request',
 '["data", "behavior", "engagement"]'::jsonb,
 '{"free_tier_requests": 250}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_engagement_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.behavior.feature_usage', 'User Feature Usage', 'DATA-FEATURE-USAGE',
 'Feature usage analysis query exposed by isA_Data',
 'data_products', 'data_processing', 0.0050, 'USD', 'per_request',
 '["data", "behavior", "feature-usage"]'::jsonb,
 '{"free_tier_requests": 250}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_feature_usage_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.analytics.user_trends', 'User Trends Analysis', 'DATA-USER-TRENDS',
 'User trends analytics query exposed by isA_Data',
 'data_products', 'data_processing', 0.0060, 'USD', 'per_request',
 '["data", "analytics", "trends"]'::jsonb,
 '{"free_tier_requests": 250}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_trends_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.analytics.churn_predictions', 'Churn Prediction', 'DATA-CHURN',
 'User churn prediction query exposed by isA_Data',
 'data_products', 'data_processing', 0.0100, 'USD', 'per_request',
 '["data", "analytics", "prediction", "churn"]'::jsonb,
 '{"free_tier_requests": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_churn_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.analytics.ltv_predictions', 'LTV Prediction', 'DATA-LTV',
 'User lifetime value prediction query exposed by isA_Data',
 'data_products', 'data_processing', 0.0100, 'USD', 'per_request',
 '["data", "analytics", "prediction", "ltv"]'::jsonb,
 '{"free_tier_requests": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_ltv_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.analytics.intent_predictions', 'Intent Prediction', 'DATA-INTENT',
 'User intent prediction query exposed by isA_Data',
 'data_products', 'data_processing', 0.0100, 'USD', 'per_request',
 '["data", "analytics", "prediction", "intent"]'::jsonb,
 '{"free_tier_requests": 100}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "user_intent_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.recommendations.graph_recommendations', 'Graph Recommendations', 'DATA-GRAPH-RECS',
 'Graph recommendation query exposed by isA_Data',
 'data_products', 'data_processing', 0.0080, 'USD', 'per_request',
 '["data", "recommendations", "graph"]'::jsonb,
 '{"free_tier_requests": 200}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "graph_recommendations_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.recommendations.content_recommendations', 'Content Recommendations', 'DATA-CONTENT-RECS',
 'Content recommendation query exposed by isA_Data',
 'data_products', 'data_processing', 0.0080, 'USD', 'per_request',
 '["data", "recommendations", "content"]'::jsonb,
 '{"free_tier_requests": 200}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "content_recommendations_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.recommendations.product_recommendations', 'Product Recommendations', 'DATA-PRODUCT-RECS',
 'Product recommendation query exposed by isA_Data',
 'data_products', 'data_processing', 0.0080, 'USD', 'per_request',
 '["data", "recommendations", "product"]'::jsonb,
 '{"free_tier_requests": 200}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "product_recommendations_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods'),

('gold.recommendations.social_recommendations', 'Social Recommendations', 'DATA-SOCIAL-RECS',
 'Social recommendation query exposed by isA_Data',
 'data_products', 'data_processing', 0.0080, 'USD', 'per_request',
 '["data", "recommendations", "social"]'::jsonb,
 '{"free_tier_requests": 200}'::jsonb,
 TRUE,
 '{"provider": "internal", "service_type": "data_service", "operation_type": "social_recommendations_query", "unit": "request"}'::jsonb,
 'digital', 'digital', 'infinite', FALSE, 'digital_goods')
ON CONFLICT (product_id) DO UPDATE SET
    product_name = EXCLUDED.product_name,
    product_code = EXCLUDED.product_code,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    product_type = EXCLUDED.product_type,
    base_price = EXCLUDED.base_price,
    billing_interval = EXCLUDED.billing_interval,
    features = EXCLUDED.features,
    quota_limits = EXCLUDED.quota_limits,
    is_active = EXCLUDED.is_active,
    metadata = EXCLUDED.metadata,
    product_kind = EXCLUDED.product_kind,
    fulfillment_type = EXCLUDED.fulfillment_type,
    inventory_policy = EXCLUDED.inventory_policy,
    requires_shipping = EXCLUDED.requires_shipping,
    tax_category = EXCLUDED.tax_category,
    updated_at = NOW();

INSERT INTO product.product_pricing (
    pricing_id, product_id, tier_name,
    min_quantity, max_quantity,
    unit_price, currency, metadata
) VALUES
('pricing_web_search_default', 'web_search', 'default', 0, NULL, 0.0020, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_web_deep_search_default', 'web_deep_search', 'default', 0, NULL, 0.0100, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_web_search_summary_default', 'web_search_summary', 'default', 0, NULL, 0.0080, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_web_automation_default', 'web_automation', 'default', 0, NULL, 0.0200, 'USD',
 '{"unit": "execution", "billing_type": "usage_based"}'::jsonb),
('pricing_python_repl_execution_default', 'python_repl_execution', 'default', 0, NULL, 0.0050, 'USD',
 '{"unit": "execution", "billing_type": "usage_based"}'::jsonb),
('pricing_customer_360_default', 'gold.analytics.customer_360', 'default', 0, NULL, 0.0040, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_user_order_history_default', 'curated.order.user_order_history', 'default', 0, NULL, 0.0030, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_user_patterns_default', 'gold.behavior.user_patterns', 'default', 0, NULL, 0.0060, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_user_journeys_default', 'gold.behavior.user_journeys', 'default', 0, NULL, 0.0060, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_engagement_metrics_default', 'gold.behavior.engagement_metrics', 'default', 0, NULL, 0.0050, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_feature_usage_default', 'gold.behavior.feature_usage', 'default', 0, NULL, 0.0050, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_user_trends_default', 'gold.analytics.user_trends', 'default', 0, NULL, 0.0060, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_churn_predictions_default', 'gold.analytics.churn_predictions', 'default', 0, NULL, 0.0100, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_ltv_predictions_default', 'gold.analytics.ltv_predictions', 'default', 0, NULL, 0.0100, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_intent_predictions_default', 'gold.analytics.intent_predictions', 'default', 0, NULL, 0.0100, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_graph_recommendations_default', 'gold.recommendations.graph_recommendations', 'default', 0, NULL, 0.0080, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_content_recommendations_default', 'gold.recommendations.content_recommendations', 'default', 0, NULL, 0.0080, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_product_recommendations_default', 'gold.recommendations.product_recommendations', 'default', 0, NULL, 0.0080, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb),
('pricing_social_recommendations_default', 'gold.recommendations.social_recommendations', 'default', 0, NULL, 0.0080, 'USD',
 '{"unit": "request", "billing_type": "usage_based"}'::jsonb)
ON CONFLICT (pricing_id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    tier_name = EXCLUDED.tier_name,
    min_quantity = EXCLUDED.min_quantity,
    max_quantity = EXCLUDED.max_quantity,
    unit_price = EXCLUDED.unit_price,
    currency = EXCLUDED.currency,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
