-- 019_add_local_gpu_inference_skus.sql
-- Adds runtime-dimension pricing defaults for local GPU inference engines.
-- These rows intentionally use NULL model_name so product_service can
-- fall back to engine-level pricing when model-specific catalog rows do not exist.

INSERT INTO product.cost_definitions (
    cost_id,
    product_id,
    service_type,
    provider,
    model_name,
    operation_type,
    cost_per_unit,
    unit_type,
    unit_size,
    original_cost_usd,
    margin_percentage,
    effective_from,
    effective_until,
    free_tier_limit,
    free_tier_period,
    is_active,
    description,
    metadata,
    created_at,
    updated_at
) VALUES
    (
        'cost_local_gpu_vllm_input',
        NULL,
        'model_inference',
        'vllm',
        NULL,
        'input',
        52,
        'token',
        1000,
        0.0004,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU VLLM input token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"vllm","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_vllm_output',
        NULL,
        'model_inference',
        'vllm',
        NULL,
        'output',
        208,
        'token',
        1000,
        0.0016,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU VLLM output token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"vllm","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_sglang_input',
        NULL,
        'model_inference',
        'sglang',
        NULL,
        'input',
        46,
        'token',
        1000,
        0.00035,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU SGLang input token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"sglang","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_sglang_output',
        NULL,
        'model_inference',
        'sglang',
        NULL,
        'output',
        184,
        'token',
        1000,
        0.0014,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU SGLang output token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"sglang","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_triton_input',
        NULL,
        'model_inference',
        'triton',
        NULL,
        'input',
        65,
        'token',
        1000,
        0.0005,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU Triton input token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"triton","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_triton_output',
        NULL,
        'model_inference',
        'triton',
        NULL,
        'output',
        260,
        'token',
        1000,
        0.0020,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU Triton output token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"triton","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_onnx_input',
        NULL,
        'model_inference',
        'onnx',
        NULL,
        'input',
        39,
        'token',
        1000,
        0.0003,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU ONNX input token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"onnx","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_onnx_output',
        NULL,
        'model_inference',
        'onnx',
        NULL,
        'output',
        156,
        'token',
        1000,
        0.0012,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Local GPU ONNX output token pricing fallback (per 1K tokens)',
        '{"backend":"local_gpu","engine_used":"onnx","sku_family":"local_gpu_inference"}'::jsonb,
        NOW(),
        NOW()
    )
ON CONFLICT (cost_id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    service_type = EXCLUDED.service_type,
    provider = EXCLUDED.provider,
    model_name = EXCLUDED.model_name,
    operation_type = EXCLUDED.operation_type,
    cost_per_unit = EXCLUDED.cost_per_unit,
    unit_type = EXCLUDED.unit_type,
    unit_size = EXCLUDED.unit_size,
    original_cost_usd = EXCLUDED.original_cost_usd,
    margin_percentage = EXCLUDED.margin_percentage,
    effective_from = EXCLUDED.effective_from,
    effective_until = EXCLUDED.effective_until,
    free_tier_limit = EXCLUDED.free_tier_limit,
    free_tier_period = EXCLUDED.free_tier_period,
    is_active = EXCLUDED.is_active,
    description = EXCLUDED.description,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
