-- 021_add_inference_surface_products.sql
-- Generic service-surface SKUs used by isa_model billing guardrails.

INSERT INTO product.products (
    product_id,
    product_name,
    product_code,
    description,
    category,
    product_type,
    base_price,
    currency,
    billing_interval,
    features,
    quota_limits,
    is_active,
    metadata,
    product_kind,
    fulfillment_type,
    inventory_policy,
    requires_shipping,
    tax_category
) VALUES
    (
        'api',
        'Model API Surface',
        'MODEL_API_SURFACE',
        'Generic isA Model API request surface for billing and catalog alignment.',
        'ai_models',
        'model_inference',
        0,
        'USD',
        'per_request',
        '["api", "model_inference"]'::jsonb,
        '{}'::jsonb,
        TRUE,
        '{"surface":"api"}'::jsonb,
        'service',
        'digital',
        'unlimited',
        FALSE,
        'digital_service'
    ),
    (
        'local-gpu',
        'Local GPU Inference Surface',
        'LOCAL_GPU_INFERENCE',
        'Generic local GPU inference surface for vLLM, SGLang, Triton, and Ray-backed runtimes.',
        'ai_models',
        'model_inference',
        0,
        'USD',
        'per_token',
        '["local_gpu", "ray_serve", "model_inference"]'::jsonb,
        '{}'::jsonb,
        TRUE,
        '{"surface":"local-gpu"}'::jsonb,
        'service',
        'digital',
        'unlimited',
        FALSE,
        'digital_service'
    ),
    (
        'cloud-gpu',
        'Cloud GPU Inference Surface',
        'CLOUD_GPU_INFERENCE',
        'Generic cloud GPU inference surface for Modal, Runpod, and managed GPU backends.',
        'ai_models',
        'model_inference',
        0,
        'USD',
        'per_token',
        '["cloud_gpu", "modal", "runpod", "model_inference"]'::jsonb,
        '{}'::jsonb,
        TRUE,
        '{"surface":"cloud-gpu"}'::jsonb,
        'service',
        'digital',
        'unlimited',
        FALSE,
        'digital_service'
    )
ON CONFLICT (product_id) DO UPDATE SET
    product_name = EXCLUDED.product_name,
    product_code = EXCLUDED.product_code,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    product_type = EXCLUDED.product_type,
    features = EXCLUDED.features,
    metadata = EXCLUDED.metadata,
    is_active = TRUE,
    updated_at = NOW();
