-- 021_add_local_gpu_shared_runtime_components.sql
-- Adds hybrid compute-aware shared local GPU pricing components.
-- Token rows remain the primary customer-facing fallback. These component rows
-- expose GPU-runtime pricing dimensions so callers can compute hybrid totals.

INSERT INTO product.cost_definitions (
    cost_id,
    product_id,
    service_type,
    provider,
    model_name,
    operation_type,
    cost_per_unit,
    unit_type,
    unit_size,
    original_cost_usd,
    margin_percentage,
    effective_from,
    effective_until,
    free_tier_limit,
    free_tier_period,
    is_active,
    description,
    metadata,
    created_at,
    updated_at
) VALUES
    (
        'cost_local_gpu_shared_gpu_seconds',
        NULL,
        'model_inference',
        NULL,
        NULL,
        'gpu_seconds',
        24,
        'second',
        1,
        0.00018,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU runtime fallback pricing (per GPU-second)',
        '{"backend":"local_gpu","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"gpu_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_vllm_gpu_seconds',
        NULL,
        'model_inference',
        'vllm',
        NULL,
        'gpu_seconds',
        22,
        'second',
        1,
        0.00017,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU VLLM runtime pricing (per GPU-second)',
        '{"backend":"local_gpu","engine_used":"vllm","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"gpu_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_sglang_gpu_seconds',
        NULL,
        'model_inference',
        'sglang',
        NULL,
        'gpu_seconds',
        20,
        'second',
        1,
        0.00015,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU SGLang runtime pricing (per GPU-second)',
        '{"backend":"local_gpu","engine_used":"sglang","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"gpu_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_triton_gpu_seconds',
        NULL,
        'model_inference',
        'triton',
        NULL,
        'gpu_seconds',
        30,
        'second',
        1,
        0.00023,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU Triton runtime pricing (per GPU-second)',
        '{"backend":"local_gpu","engine_used":"triton","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"gpu_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_onnx_gpu_seconds',
        NULL,
        'model_inference',
        'onnx',
        NULL,
        'gpu_seconds',
        16,
        'second',
        1,
        0.00012,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU ONNX runtime pricing (per GPU-second)',
        '{"backend":"local_gpu","engine_used":"onnx","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"gpu_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_shared_prefill_seconds',
        NULL,
        'model_inference',
        NULL,
        NULL,
        'prefill_seconds',
        10,
        'second',
        1,
        0.00008,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU prefill surcharge pricing (per second)',
        '{"backend":"local_gpu","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"prefill_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_shared_queue_seconds',
        NULL,
        'model_inference',
        NULL,
        NULL,
        'queue_seconds',
        4,
        'second',
        1,
        0.00003,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU queueing surcharge pricing (per second)',
        '{"backend":"local_gpu","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"queue_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_shared_cold_start_seconds',
        NULL,
        'model_inference',
        NULL,
        NULL,
        'cold_start_seconds',
        12,
        'second',
        1,
        0.00009,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU cold start surcharge pricing (per second)',
        '{"backend":"local_gpu","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"cold_start_seconds"}'::jsonb,
        NOW(),
        NOW()
    ),
    (
        'cost_local_gpu_shared_kv_cache_gib_seconds',
        NULL,
        'model_inference',
        NULL,
        NULL,
        'kv_cache_gib_seconds',
        2,
        'gib_second',
        1,
        0.000015,
        30.0,
        NOW(),
        NULL,
        0,
        'monthly',
        TRUE,
        'Shared local GPU KV-cache residency pricing (per GiB-second)',
        '{"backend":"local_gpu","sku_family":"local_gpu_inference","tenancy_mode":"shared","pricing_dimension":"kv_cache_gib_seconds"}'::jsonb,
        NOW(),
        NOW()
    )
ON CONFLICT (cost_id) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    service_type = EXCLUDED.service_type,
    provider = EXCLUDED.provider,
    model_name = EXCLUDED.model_name,
    operation_type = EXCLUDED.operation_type,
    cost_per_unit = EXCLUDED.cost_per_unit,
    unit_type = EXCLUDED.unit_type,
    unit_size = EXCLUDED.unit_size,
    original_cost_usd = EXCLUDED.original_cost_usd,
    margin_percentage = EXCLUDED.margin_percentage,
    effective_from = EXCLUDED.effective_from,
    effective_until = EXCLUDED.effective_until,
    free_tier_limit = EXCLUDED.free_tier_limit,
    free_tier_period = EXCLUDED.free_tier_period,
    is_active = EXCLUDED.is_active,
    description = EXCLUDED.description,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
