{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: isa-user
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
{{- end }}
