-- Device Service Test Data
-- Standardized test data following test_data_standard.md
-- Date: 2025-11-11

-- Insert test devices
INSERT INTO device.devices (
    device_id,
    user_id,
    organization_id,
    device_name,
    device_type,
    manufacturer,
    model,
    serial_number,
    firmware_version,
    hardware_version,
    mac_address,
    connectivity_type,
    security_level,
    status,
    location,
    metadata,
    tags,
    total_commands,
    total_telemetry_points,
    uptime_percentage,
    registered_at,
    updated_at,
    last_seen
) VALUES
-- Device 1: Smart Frame (active)
(
    'test_device_001',
    'test_user_001',
    'test_org_001',
    'Living Room Smart Frame',
    'smart_frame',
    'SmartFrame Inc',
    'SF-2024-Pro',
    'SF2024-001-PROD',
    '2.1.0',
    'v2.0',
    'AA:BB:CC:DD:EE:01',
    'wifi',
    'standard',
    'active',
    '{"latitude": 39.9042, "longitude": 116.4074, "address": "Beijing, China"}',
    '{"location_name": "Living Room", "floor": 1}',
    ARRAY['production', 'smart_frame', 'living_room'],
    25,
    1500,
    98.5,
    NOW() - INTERVAL '30 days',
    NOW(),
    NOW() - INTERVAL '5 minutes'
),

-- Device 2: Smart Frame (inactive)
(
    'test_device_002',
    'test_user_001',
    'test_org_001',
    'Bedroom Smart Frame',
    'smart_frame',
    'SmartFrame Inc',
    'SF-2024-Basic',
    'SF2024-002-PROD',
    '2.0.5',
    'v2.0',
    'AA:BB:CC:DD:EE:02',
    'wifi',
    'standard',
    'inactive',
    '{"latitude": 39.9042, "longitude": 116.4074, "address": "Beijing, China"}',
    '{"location_name": "Bedroom", "floor": 2}',
    ARRAY['production', 'smart_frame', 'bedroom'],
    10,
    800,
    75.0,
    NOW() - INTERVAL '60 days',
    NOW() - INTERVAL '7 days',
    NOW() - INTERVAL '2 days'
),

-- Device 3: Sensor (active)
(
    'test_device_003',
    'test_user_001',
    NULL,
    'Temperature Sensor 01',
    'sensor',
    'IoT Sensors Corp',
    'TEMP-100',
    'TEMP100-003-PROD',
    '1.5.2',
    'v1.0',
    'AA:BB:CC:DD:EE:03',
    'zigbee',
    'basic',
    'active',
    '{"latitude": 39.9042, "longitude": 116.4074}',
    '{"sensor_type": "temperature", "unit": "celsius"}',
    ARRAY['sensor', 'temperature', 'zigbee'],
    5,
    5000,
    99.2,
    NOW() - INTERVAL '90 days',
    NOW(),
    NOW() - INTERVAL '1 minute'
),

-- Device 4: Camera (maintenance)
(
    'test_device_004',
    'test_user_002',
    'test_org_002',
    'Front Door Camera',
    'camera',
    'SecureCam Ltd',
    'CAM-2024-HD',
    'CAM2024-004-PROD',
    '3.2.1',
    'v3.0',
    'AA:BB:CC:DD:EE:04',
    'wifi',
    'high',
    'maintenance',
    '{"latitude": 40.7128, "longitude": -74.0060, "address": "New York, USA"}',
    '{"resolution": "1080p", "night_vision": true}',
    ARRAY['camera', 'security', 'outdoor'],
    100,
    25000,
    95.8,
    NOW() - INTERVAL '120 days',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '6 hours'
),

-- Device 5: Gateway (active)
(
    'test_device_005',
    'test_user_001',
    'test_org_001',
    'Main Gateway',
    'gateway',
    'IoT Gateway Corp',
    'GW-2024',
    'GW2024-005-PROD',
    '4.0.0',
    'v4.0',
    'AA:BB:CC:DD:EE:05',
    'ethernet',
    'critical',
    'active',
    '{"latitude": 39.9042, "longitude": 116.4074}',
    '{"max_devices": 100, "protocols": ["zigbee", "zwave", "bluetooth"]}',
    ARRAY['gateway', 'critical', 'infrastructure'],
    500,
    100000,
    99.9,
    NOW() - INTERVAL '180 days',
    NOW(),
    NOW() - INTERVAL '30 seconds'
)
ON CONFLICT (device_id) DO NOTHING;

-- Insert test device groups
INSERT INTO device.device_groups (
    group_id,
    user_id,
    organization_id,
    group_name,
    description,
    parent_group_id,
    tags,
    metadata,
    device_count,
    created_at,
    updated_at
) VALUES
(
    'test_group_001',
    'test_user_001',
    'test_org_001',
    'Living Room Devices',
    'All smart devices in the living room',
    NULL,
    ARRAY['living_room', 'smart_home'],
    '{"floor": 1, "room_type": "living_room"}',
    0,
    NOW() - INTERVAL '30 days',
    NOW()
),
(
    'test_group_002',
    'test_user_001',
    'test_org_001',
    'Security Devices',
    'All security cameras and sensors',
    NULL,
    ARRAY['security', 'surveillance'],
    '{"priority": "high"}',
    0,
    NOW() - INTERVAL '60 days',
    NOW()
),
(
    'test_group_003',
    'test_user_002',
    'test_org_002',
    'Outdoor Devices',
    'All outdoor IoT devices',
    NULL,
    ARRAY['outdoor', 'weather_resistant'],
    '{}',
    0,
    NOW() - INTERVAL '45 days',
    NOW()
)
ON CONFLICT (group_id) DO NOTHING;

-- Insert test frame configs for smart frames
INSERT INTO device.frame_configs (
    device_id,
    brightness,
    contrast,
    auto_brightness,
    orientation,
    slideshow_interval,
    slideshow_transition,
    shuffle_photos,
    show_metadata,
    sleep_schedule,
    auto_sleep,
    motion_detection,
    auto_sync_albums,
    sync_frequency,
    wifi_only_sync,
    display_mode,
    location,
    timezone,
    created_at,
    updated_at
) VALUES
(
    'test_device_001',
    80,
    100,
    true,
    'auto',
    30,
    'fade',
    true,
    false,
    '{"start": "23:00", "end": "07:00"}',
    true,
    true,
    ARRAY['test_album_001', 'test_album_002'],
    'hourly',
    true,
    'photo_slideshow',
    '{"latitude": 39.9042, "longitude": 116.4074}',
    'Asia/Shanghai',
    NOW() - INTERVAL '30 days',
    NOW()
),
(
    'test_device_002',
    70,
    90,
    false,
    'landscape',
    60,
    'slide',
    false,
    true,
    '{"start": "22:00", "end": "08:00"}',
    true,
    false,
    ARRAY['test_album_003'],
    'daily',
    true,
    'photo_slideshow',
    '{"latitude": 39.9042, "longitude": 116.4074}',
    'Asia/Shanghai',
    NOW() - INTERVAL '60 days',
    NOW() - INTERVAL '7 days'
)
ON CONFLICT (device_id) DO NOTHING;

-- Insert test device commands
INSERT INTO device.device_commands (
    command_id,
    device_id,
    user_id,
    command,
    parameters,
    timeout,
    priority,
    require_ack,
    status,
    result,
    created_at,
    sent_at,
    acknowledged_at,
    completed_at
) VALUES
(
    'test_command_001',
    'test_device_001',
    'test_user_001',
    'display_photo',
    '{"photo_id": "test_photo_001", "duration": 30}',
    30,
    5,
    true,
    'executed',
    '{"success": true, "display_time": 30}',
    NOW() - INTERVAL '1 hour',
    NOW() - INTERVAL '59 minutes',
    NOW() - INTERVAL '58 minutes',
    NOW() - INTERVAL '58 minutes'
),
(
    'test_command_002',
    'test_device_001',
    'test_user_001',
    'start_slideshow',
    '{"album_id": "test_album_001"}',
    30,
    3,
    true,
    'executed',
    '{"success": true, "photos_count": 25}',
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '29 minutes',
    NOW() - INTERVAL '29 minutes',
    NOW() - INTERVAL '28 minutes'
),
(
    'test_command_003',
    'test_device_003',
    'test_user_001',
    'get_temperature',
    '{}',
    10,
    7,
    true,
    'executed',
    '{"success": true, "temperature": 24.5, "unit": "celsius"}',
    NOW() - INTERVAL '5 minutes',
    NOW() - INTERVAL '4 minutes 50 seconds',
    NOW() - INTERVAL '4 minutes 48 seconds',
    NOW() - INTERVAL '4 minutes 48 seconds'
),
(
    'test_command_004',
    'test_device_002',
    'test_user_001',
    'sync_album',
    '{"album_id": "test_album_003"}',
    60,
    2,
    true,
    'failed',
    NULL,
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '119 minutes',
    NULL,
    NOW() - INTERVAL '118 minutes'
),
(
    'test_command_005',
    'test_device_004',
    'test_user_002',
    'start_recording',
    '{"duration": 300, "quality": "HD"}',
    30,
    8,
    true,
    'pending',
    NULL,
    NOW() - INTERVAL '2 minutes',
    NULL,
    NULL,
    NULL
)
ON CONFLICT (command_id) DO NOTHING;

-- Verify data
SELECT 'Devices inserted:' as info, COUNT(*) as count FROM device.devices WHERE device_id LIKE 'test_%';
SELECT 'Device groups inserted:' as info, COUNT(*) as count FROM device.device_groups WHERE group_id LIKE 'test_%';
SELECT 'Frame configs inserted:' as info, COUNT(*) as count FROM device.frame_configs WHERE device_id LIKE 'test_%';
SELECT 'Device commands inserted:' as info, COUNT(*) as count FROM device.device_commands WHERE command_id LIKE 'test_%';
